### PR TITLE
Feature/cs/whats this links

### PR DESCRIPTION
**Pull request by cjshawMIT**
Adds `What's this` and help links to the following things:

- Top-right of window
- Question types when adding new questions
- Question text field
- Help button for each question type
- Publish button

Screenshots below. Probably needs lots of styling improvements.
captura de pantalla 2017-11-20 a la s 3 41 26 pm
captura de pantalla 2017-11-20 a la s 3 41 30 pm
captura de pantalla 2017-11-20 a la s 3 41 39 pm

### CODE REVIEW

**Comment by cjshawMIT** [comment]
Ignoring the two `react/no-typos` Hound violations, because I don't see any typos...

**Comment by cjshawMIT** [comment]
Please ignore all the hound violations for the `toc` library...we can't control that.

**Comment by cjshawMIT** [comment]
@resource11 not sure why Hound is not picking up on the ignore config still, but please ignore all the violations from `client/static/vendor/`...

**Comment by resource11** [comment]
Great start! Here are four things:

1: Have we made a transcript for that DnD demo video? We'll need to integrate that here.

2. When we're in the help section, we need to allow the user to navigate through the entire section if desired, i.e., the Getting Started, Authoring Questions, Publishing Workflow need to be reachable always no matter where you enter the help section.

3. Are we purposefully opening a separate tab to display the help section?

4. The images probably could benefit from some file-size optimization and preparation. Ideally, we should be serving them up as responsive images. We should open an issue for this; I can prep those and show you a good way to add responsive image functionality.

**Comment by cjshawMIT** [comment]
1) No transcript, good idea. I'll transcribe one.
2) Hm....how do you suggest doing this? At one point we talked about some sort of help menu or landing page, but I thought we decided not to do that. Suggestions on a good nav between sections?
3) My thought was just that if you open in a new tab, you can toggle or put side-by-side the help and the actual authoring interface. If you open it in the same tab, then that seems less user-friendly -- you can keep hitting back / forward, but the authoring tool won't open back up at the same point it was previously (especially on the specific question that was expanded).
4) Thanks, that would be helpful.

**Comment by resource11** [comment]
1. Cool on the transcript. I need to give you a pattern for toggling the transcript in and out of view.
2. For navigating to the help section you can link to a URL fragment in another page. You're already doing this when you're linking to the `Authoring Workflow` section from the `What's this?` in the MC authoring UI region. The links for `Getting Started` and `Publishing Workflow` don't link this way. Once everything is in the same page, we'll definitely need to link to URL fragments consistently. There's a rub, though. The `id` attributes in the all three pages are not unique. We'll have to fix that. 
2a. When we combine pages and do a css cleanup pass of the help page, we also need to restructure the headings. Currently more than one `h1` on all pages. We can add `Getting Started As an Author` as the `h1` of the help page, and migrate the heading structure of all the other content one level down, starting with `h2`.

3. I'm wondering if we should consider making the help section a panel that slides in over the content, where you can close it when you're done. That way, you will return to the place you left off when you need help. Alternately, a modal that slides in that shows links to the three major help sections, then the user navigates to new browser tab upon selection of the major section. Do we have time to do it this way, is another question.

**Comment by cjshawMIT** [comment]
I don't understand what you mean by `Getting Started` and `Publishing Workflow` aren't linked to specific sections -- each of those only has one link to it, so I was assuming the entire page is treated as one help section. Do you think there should be pointers to sub-sections of those pages, and if so, where should those go? Is that what you meant?

I'm also unclear what you mean by putting all three into one page -- is that your suggestion? I think at our last meeting with Kirky we had agreed on having the three pages to address three different topics, and keeping them separate. The IDs are generated by the TOC library, so wouldn't be a problem.

We can definitely clean things up. They are currently just converted over from markdown into HTML from the GitHub wiki, so most of the formatting was just automated.

Modals and drawers might prevent you from navigating to a specific section / ID, unless you add a library or something? I'm not sure, but those solutions seem like they work around the browser's built-in # feature that lets us currently jump to an id.

**Comment by resource11** [comment]
I can show you better examples on what I mean about the help section on Monday. Will that be easier?

**Comment by cjshawMIT** [comment]
Sure, sounds good.

**Comment by cjshawMIT** [comment]
@resource11 I believe I've addressed all comments for help, to create a working-but-ugly version. Please ignore Hound... Updates to the PR:

- Single `Help` page with three sections
- Use VideoJS as the player
- Transcript toggle (using the input checkbox method)
- CSS compiles like for player and author, so you should be able to use SASS

I also tried incorporating the style files from the [ART template repo](https://github.com/CLIxIndia-Dev/ART-transcript-patterns), but ran into lots of weird issues (I.e. the TOC was no longer indented, no margins on the page, and also VideoJS player looks very weird -- the audio slider was below the video component and no CC icon, but you could click on it).

To see the pretty-but-broken version, you can go into `client/styles/_help` and rename `styles.css` to `ugly-styles.css` and then `styles-desired.css` to `styles.css`. You should also be able to remove the explicit `video-js.min.css` stylesheet `link` in the new Help template at `client/html/layouts/Help.html`. Any changes you need to make to the actual help content / video element can be done with the `_help.html` partial located at `client/html/layouts/partials/_help.html`.

**Pull request merged**
